spring:
  application:
    name: 03_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          clone-on-start: true 
    
server:
  port: 2222
  